name: creditoverde
description: Projeto de ajuda de produtores rurais de pequeno e medio porte
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  flutter_timer_countdown: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  image_path: "assets/main-logo.png"
  android: true
  remove_alpha_ios: true
  ios: true

flutter_native_splash:
  color: "#7bAe4e"
  image: assets/splash-screen-logo.png
  android_12:
    color: "#7bAe4e"

flutter:
  uses-material-design: true
  assets:
    - assets/login/
    - assets/cards/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
